/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'mens' : null } |
  { 'collections' : null } |
  { 'necklaces' : null } |
  { 'earrings' : null } |
  { 'rings' : null } |
  { 'bracelets' : null };
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'weightGrams' : number,
  'makingCharge' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getGoldPrice' : ActorMethod<[], bigint>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGoldPrice' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];